### ISSUE TITLE
Issue with git cloning and installing dependencies..

### ISSUE THREAD

**Issue by pratik2394** [hietalajulius/cloth-manipulation#1]
upon running this command 'git clone git@github.com:hietalajulius/dynamic-cloth-folding.git --recursive' it says 

Cloning into 'dynamic-cloth-folding'...
Warning: Permanently added the ECDSA host key for IP address '140.82.114.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
...

Problem2:
If I download the package manually, and run 'cd dynamic-cloth-folding && ./install-dependencies.sh'

it gives the following errors...

a.
Successfully installed dynamic-cloth-folding-0.2.1.dev0
~/dynamic-cloth-folding/submodules/mujoco-py ~/dynamic-cloth-folding
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

b.
~/dynamic-cloth-folding/submodules/robosuite ~/dynamic-cloth-folding
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-extra.txt'

c.
Obtaining file:///home/pratik/dynamic-cloth-folding/submodules/robosuite
ERROR: file:///home/pratik/dynamic-cloth-folding/submodules/robosuite does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

d. ~/dynamic-cloth-folding/submodules/rlkit ~/dynamic-cloth-folding
Obtaining file:///home/pratik/dynamic-cloth-folding/submodules/rlkit
ERROR: file:///home/pratik/dynamic-cloth-folding/submodules/rlkit does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

e.
Obtaining file:///home/pratik/dynamic-cloth-folding/osc-controller-binding
  Preparing metadata (setup.py) ... done
Installing collected packages: osc-binding
  Running setup.py develop for osc-binding
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [81 lines of output]

f. 
note: This error originates from a subprocess, and is likely not a problem with pip.
~/dynamic-cloth-folding

any help is appreciated.

**Comment by hietalajulius** [comment]
Thanks for letting me know! Could you try `git clone https://github.com/hietalajulius/dynamic-cloth-folding.git --recursive` instead, sounds like something may be wrong with your ssh setup.

**Comment by pratik2394** [comment]
Hi, Thank you for the response. I did solve SSH issue.

I tried the above command but some of the submodules required SSH key. So, SSH key is irreplaceable requirement.
