### ISSUE TITLE
Real world experiments

### ISSUE THREAD

**Issue by SiyuanHuang95** [hietalajulius/cloth-manipulation#2]
Hi,

thanks for sharing!

I would like to try your method with a franka panda, could you give more details w.r.t the setup?

Also, I am wandering wether the pre-trained cpkt will be available. 

Bests

**Comment by hietalajulius** [comment]
Hi! Unfortunately I don't have a polished version of the real-world code available, but you can email me and I can share the code.

**Comment by zcswdt** [comment]
> Hi! Unfortunately I don't have a polished version of the real-world code available, but you can email me and I can share the code.

Hello, I have sent you an email, but unfortunately I did not receive your reply. I am not sure if the email I sent is your commonly used email! Can you share a copy of this code with me? My email is `jhsignal@126.com` ，Looking forward to your reply! Thank you very much

**Comment by hietalajulius** [comment]
Hi!

Sorry for the delay here!

I added you to the repo, it is not polished at all / does not have clear instructions so I won’t make it public. Let me know if you end up making a more polished version I could make public.

Thanks,
Julius

**Comment by zcswdt** [comment]
Hi,

Thank you very much for your reply and for sharing the real world code with me. This will be very helpful to me. I will repeat your experiment and refer to your method. If I could improve your code, I would share it with you and once again express my gratitude to you.




Thanks，
zcs




At 2023-07-18 19:01:32, "Julius Hietala" ***@***.***> wrote:

Hi!

Sorry for the delay here!

I added you to the repo, it is not polished at all / does not have clear instructions so I won’t make it public. Let me know if you end up making a more polished version I could make public.

Thanks,
Julius

**Comment by hietalajulius** [comment]
You may need to edit the code quite a bit to get it running, unfortunately I did not document it very well, just needed to “make it work” for my experiments in our lab setup. However all the building blocks should be there. Also please refer to the blog posts on the paper which may reveal some gotchas: ***@***.***/learning-visual-feedback-control-for-dynamic-cloth-folding-what-the-paper-does-not-tell-you-2-3-e4a8ac72c1e1

Thanks,
Julius

**Comment by zcswdt** [comment]
Hi:

It's okay, give me your code as a reference to learn how you came up with such a good method and implemented it. My main focus is to learn from your ideas. Also, regarding the blog you mentioned in your email, I couldn't find the desired website address. How can I proceed,




Thanks,
zcs




At 2023-07-19 17:34:33, "Julius Hietala" ***@***.***> wrote:

You may need to edit the code quite a bit to get it running, unfortunately I did not document it very well, just needed to “make it work” for my experiments in our lab setup. However all the building blocks should be there. Also please refer to the blog posts on the paper which may reveal some gotchas: ***@***.***/learning-visual-feedback-control-for-dynamic-cloth-folding-what-the-paper-does-not-tell-you-2-3-e4a8ac72c1e1

Thanks,
Julius

**Comment by hietalajulius** [comment]
Sounds great!

Here’s an alternative link to my personal blog: https://www.juliushietala.com/blog <https://www.juliushietala.com/blog>

Julius

**Comment by zcswdt** [comment]
You are really great. Thank you for sharing your research results with me. This will definitely make me progress quickly in the future. Your academic achievements have impressed me, and thank you for guiding me in the direction.
















在 2023-07-19 19:33:39，"Julius Hietala" ***@***.***> 写道：

Sounds great!

Here’s an alternative link to my personal blog: https://www.juliushietala.com/blog <https://www.juliushietala.com/blog>

Julius

**Comment by hietalajulius** [comment]
Thanks, let me know how it goes!

Julius

**Comment by foreback** [comment]
Hello,

I hope this message finds you well. I recently sent you an email regarding your impressive project on dynamic cloth folding. I have developed a new and in-depth research idea based on your work and would like to build upon it.

To assist with my scientific research, could you please share a copy of the real-world code used in this project? If my previous email did not reach you or if it was sent to an incorrect address, please feel free to respond to this message. My email address is [zanchen@zju.edu.cn](mailto:zanchen@zju.edu.cn).

Thank you very much for your assistance. I look forward to your reply.

Best regards

**Comment by hietalajulius** [comment]
> Hello,
> 
> I hope this message finds you well. I recently sent you an email regarding your impressive project on dynamic cloth folding. I have developed a new and in-depth research idea based on your work and would like to build upon it.
> 
> To assist with my scientific research, could you please share a copy of the real-world code used in this project? If my previous email did not reach you or if it was sent to an incorrect address, please feel free to respond to this message. My email address is [zanchen@zju.edu.cn](mailto:zanchen@zju.edu.cn).
> 
> Thank you very much for your assistance. I look forward to your reply.
> 
> Best regards

Hi @foreback! For some reason I did not receive your email. I added you to the repo now, but just as a warning there is no instruction manual on how to run things, but all the code is there in some form or another.

**Comment by foreback** [comment]
> r

Thank you so much for adding me to the repository! I appreciate your quick action on this.
